### ISSUE TITLE
History page design 

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#10]
Create the lo-fi and hi-fi designs for the website history page using the defined style guide

**Comment by Mehetabelgift** [comment]
Welldone guys, please change the colours of the cards to the right one. Please, refer to the homepage to know the correct spacing and typography to use.

**Comment by Billyfaychi** [comment]
Awesome well done guys

**Comment by Billyfaychi** [comment]
We are done with this guys 😁👍
