### ISSUE TITLE
Help and feedback page design 

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#11]
Create the lo-fi and hi-fi designs for the website feedback page using the defined style guide

**Comment by blvckcoco** [comment]
I have been able to completely design them and submitted on the figma board already.

**Comment by HillaryWebb-coder** [comment]
Cool

**Comment by blvckcoco** [comment]
https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=594%3A4333
heres the link to the design as completed on the figma board
