### ISSUE TITLE
Category Page

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#15]
create the lo-fi and hi-fi designs for the website category page

**Comment by asaddo444** [comment]
Page has been created and movie lists were updated. Information and thumbnails were updated in full.

**Comment by asaddo444** [comment]
https://www.figma.com/file/8UVlg94b7hZL8Kb3of8Zay/Collywood-Categories-Page?node-id=0%3A1
