### ISSUE TITLE
Upload page 

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#7]
Create the lo-fi and hi-fi designs for the website video upload page using the defined style guide

**Comment by Mehetabelgift** [comment]
Well-done babes, please you guys haven't done the schedule page. What's going on?

**Comment by TomilayoA** [comment]
@Mehetabelgift Still working on it, I'm having light issues and Abibat's battery is faulty.
We'll work on it as soon as I charge.

Thanks.

**Comment by AbibatShittu** [comment]
@Mehetabelgift , we have done the schedule upload page o. Check it. 
As for the colour you asked us change, which colour are we using sef. We used the colour we saw on someone's hifi

**Comment by AbibatShittu** [comment]
We are done with all the assigned pages. The links are below
This is my figma link
Abibat Shittu: 

profile page: https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=1088%3A24978

schedule: https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=1088%3A24611

rules: https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=1088%3A24572

select files: https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=1088%3A24898

caption: https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=1088%3A24940

edit profile: https://www.figma.com/file/2JmfyXDioi6yalyEUThkb4/Team120_col-films-(Copy)?node-id=1088%3A25590
