### ISSUE TITLE
Categories page design 

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#8]
Create the lo-fi and hi-fi designs for the website homepage using the defined style guide

**Comment by DravidTML** [comment]
The Lofi design has been completed

**Comment by DravidTML** [comment]
Thumbnails are being added to all the video frames on the hifi.

**Comment by asaddo444** [comment]
Lofi and hifi are about completed, thumbnails have been updated

**Comment by asaddo444** [comment]
Color and styles have been formatted to web look

**Comment by DravidTML** [comment]
All category lists have been made components  with instances to implement horizontal scrolling.
