### ISSUE TITLE
Library page 

### ISSUE THREAD

**Issue by HillaryWebb-coder** [zuri-training/Col-films-Team-120#9]
Create the lo-fi and hi-fi designs for the website library page using the defined style guide

**Comment by blvckcoco** [comment]
Lo-fi and Hi-fi for Library pages executed and submitted as at yesterday which was the prescribed deadline.

**Comment by Mola71** [comment]
I did lofi  notification and also change the library page (lofi) to hifi and also helped Gift to make a little adjustment with the homepage.
